// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEfypRIfp7MPZSWTRyJ-K0K-gvxbG9tcs',
    appId: '1:1079216154076:web:d04fc0f5a8f4d46fe05b19',
    messagingSenderId: '1079216154076',
    projectId: 'org-dont-app',
    authDomain: 'org-dont-app.firebaseapp.com',
    databaseURL: 'https://org-dont-app-default-rtdb.firebaseio.com',
    storageBucket: 'org-dont-app.firebasestorage.app',
    measurementId: 'G-JNK5YD1SB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrJfQ8DsVz4I8bLv-r5m07Q-9tCsgHO3g',
    appId: '1:1079216154076:android:9fd71b7d8d07012be05b19',
    messagingSenderId: '1079216154076',
    projectId: 'org-dont-app',
    databaseURL: 'https://org-dont-app-default-rtdb.firebaseio.com',
    storageBucket: 'org-dont-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNVVYdglX2e8lVnl61IHNmadyr2EiM-Ts',
    appId: '1:1079216154076:ios:738a2385fd23e2a1e05b19',
    messagingSenderId: '1079216154076',
    projectId: 'org-dont-app',
    databaseURL: 'https://org-dont-app-default-rtdb.firebaseio.com',
    storageBucket: 'org-dont-app.firebasestorage.app',
    iosBundleId: 'com.example.innii',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEfypRIfp7MPZSWTRyJ-K0K-gvxbG9tcs',
    appId: '1:1079216154076:web:731c3d55fbc14ae3e05b19',
    messagingSenderId: '1079216154076',
    projectId: 'org-dont-app',
    authDomain: 'org-dont-app.firebaseapp.com',
    databaseURL: 'https://org-dont-app-default-rtdb.firebaseio.com',
    storageBucket: 'org-dont-app.firebasestorage.app',
    measurementId: 'G-NJQN7R4751',
  );
}
